# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get install -y git kmod make gcc linux-headers-`uname -r`
        git clone https://github.com/remote-android/redroid-modules
        cd redroid-modules
        sudo make # build kernel modules
        sudo make install # build and install *unsigned* kernel modules
        
